## This project focuses on solving Matura exam data exercises using Pandas library

### Imporing Python libraries and creating dataframes for all given files

In [2]:
import pandas as pd
import numpy as np
from charset_normalizer import from_path
import glob

In [3]:
def kodowania_plikow(file_names):
    return {f_name: from_path(f_name).best().encoding for f_name in file_names}

f_nametab = glob.glob("*.txt")
print(kodowania_plikow(f_nametab))

{'kraje.txt': 'cp1250', 'punkty.txt': 'ascii', 'skoczek.txt': 'iso8859_16', 'skocznie.txt': 'cp1250', 'zawody.txt': 'ascii'}

In [4]:
def setting_dataframes(file_names):
    return_dct = {}
    for f_name in file_names:
        return_dct[f_name] = pd.read_csv(f_name, sep="\t", encoding="cp1250")
    return return_dct

df_dct =  setting_dataframes(f_nametab)

print(', '.join([name.strip('.txt') for name in df_dct.keys()]))

kraje, punkty, skoczek, skocznie, zawody

In [5]:
kraje, punkty, skoczek, skocznie, zawody = df_dct.values()

### EDA, Preparing dataframes for future analysis

In [6]:
print(skocznie.columns)

Index(['kod_skoczni', 'miasto', 'kod_kraju ', 'punkt_HS', 'punkt_K'], dtype='object')

In [30]:
skocznie = skocznie.rename(columns={'kod_kraju ': 'kod_kraju'})

In [8]:
print(zawody.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   miejsce        630 non-null    int64
 1   kod_zawodnika  630 non-null    object
 2   odl.1          630 non-null    object
 3   odl.2          630 non-null    object
 4   punkty         630 non-null    object
 5   skocznia       630 non-null    object
dtypes: int64(1), object(5)
memory usage: 29.7+ KB
None

In [9]:
print("odl.1 :", zawody['odl.1'].unique()[:10])
print("odl.2 :", zawody['odl.2'].unique()[:10])
print("punkty :", zawody['punkty'].unique()[:9])

odl.1 : ['123' '131' '131,5' '126' '129' '123,5' '128,5' '120,5' '128' '118,5']
odl.2 : ['132' '135' '130' '130,5' '128' '127,5' '127' '131,5' '121,5' '126']
punkty : ['282,2' '278' '277,5' '274,2' '272,4' '270,1' '269,1' '268,3' '266,5']

In [10]:
col_to_change = ['odl.1', 'odl.2', 'punkty']

for col in col_to_change:
    zawody[col] = zawody[col].str.replace(',', '.').astype(dtype=float)

zawody.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   miejsce        630 non-null    int64
 1   kod_zawodnika  630 non-null    object
 2   odl.1          630 non-null    float64
 3   odl.2          630 non-null    float64
 4   punkty         630 non-null    float64
 5   skocznia       630 non-null    object
dtypes: float64(3), int64(1), object(2)
memory usage: 29.7+ KB

In [11]:
print("odl.1 :", zawody['odl.1'].unique()[:10])
print("odl.2 :", zawody['odl.2'].unique()[:10])
print("punkty :", zawody['punkty'].unique()[:10])

odl.1 : [123.  131.  131.5 126.  129.  123.5 128.5 120.5 128.  118.5]
odl.2 : [132.  135.  130.  130.5 128.  127.5 127.  131.5 121.5 126. ]
punkty : [282.2 278.  277.5 274.2 272.4 270.1 269.1 268.3 266.5 265.2]

In [32]:
kraje.columns

Index(['kod_kraju', 'nazwa'], dtype='object')

### Task 1

In [12]:
def task_print(num):
    print(f"-------------TASK-{str(num)}-ANSWER-------------\n")

In [13]:
def merge_inner(df1, df2, df1_col, df2_col):
    return df1.merge(df2, how='inner', left_on=df1_col, right_on=df2_col)

In [14]:
task1_df = merge_inner(zawody, skoczek, 'kod_zawodnika', 'kod_skoczka')
task1_df = merge_inner(task1_df, kraje, 'kod_kraju', 'kod_kraju')

task1_df.head()

,miejsce,kod_zawodnika,odl.1,odl.2,punkty,skocznia,kod_skoczka,nazwisko_imie,kod_kraju,nazwa
0,1,sk1,123.0,132.0,282.2,s1,sk1,GRANERUD Halvor Egner,k1,Norwegia
1,2,sk2,131.0,135.0,278.0,s1,sk2,HUBER Daniel,k2,Austria
2,3,sk3,131.5,130.0,277.5,s1,sk3,GEIGER Karl,k3,Niemcy
3,4,sk4,131.5,130.5,274.2,s1,sk4,KUBACKI Dawid,k4,Polska
4,5,sk5,126.0,128.0,272.4,s1,sk5,PASCHKE Pius,k3,Niemcy

In [15]:
task1_df.sort_values('punkty', ascending=True).head(3)

,miejsce,kod_zawodnika,odl.1,odl.2,punkty,skocznia,kod_skoczka,nazwisko_imie,kod_kraju,nazwa
419,30,sk7,92.0,0.0,117.1,s14,sk7,EISENBICHLER Markus,k3,Niemcy
418,29,sk1,94.0,0.0,126.1,s14,sk1,GRANERUD Halvor Egner,k1,Norwegia
89,30,sk53,124.0,96.5,164.8,s3,sk53,PILCH Tomasz,k4,Polska

In [16]:
ans_1 = task1_df.sort_values('punkty', ascending=True).iloc[0]

task_print(1)

print(ans_1['nazwisko_imie'], "|", ans_1['nazwa'], "|", ans_1['punkty'])

-------------TASK-1-ANSWER-------------

EISENBICHLER Markus | Niemcy | 117.1

### Task 2

In [17]:
task2_df = merge_inner(skoczek, kraje, 'kod_kraju', 'kod_kraju')
task2_df = task2_df.groupby(['nazwa']).count().rename(columns={'kod_skoczka': 'suma'})[['suma']]
min_2 = task2_df.suma.min()
max_2 = task2_df.suma.max()

ans_2 = task2_df[task2_df.suma.isin([min_2, max_2])]
task_print(2)
ans_2

-------------TASK-2-ANSWER-------------

          suma
nazwa
Austria     15
Bułgaria     1
Estonia      1
Kanada       1
Włochy       1

### Task 3

In [18]:
task3_df = merge_inner(zawody, skoczek, 'kod_zawodnika', 'kod_skoczka')
task3_df = merge_inner(task3_df, kraje, 'kod_kraju', 'kod_kraju')
task3_df['suma'] = task3_df['odl.1'] + task3_df['odl.2']

task3_df = task3_df.groupby(['nazwisko_imie', 'nazwa']).suma.sum().reset_index().sort_values('suma', ascending=False)

task3_df.head()

          nazwisko_imie     nazwa    suma
34      KOBAYASHI Ryoyu   Japonia  5726.5
72          STOCH Kamil    Polska  5713.0
39        KUBACKI Dawid    Polska  5686.0
30     JOHANSSON Robert  Norwegia  5681.0
10  EISENBICHLER Markus    Niemcy  5358.5

In [19]:
ans_3 = task3_df.iloc[0]
task_print(3)
print(ans_3['nazwisko_imie'], "|", ans_3['nazwa'], "|", ans_3['suma'])

-------------TASK-3-ANSWER-------------

KOBAYASHI Ryoyu | Japonia | 5726.5

### Task 4

In [28]:
task4_df = merge_inner(zawody, punkty, 'miejsce', 'miejsce').rename(columns={'punkty_y': 'punktacja'})
task4_df = merge_inner(task4_df, skoczek, 'kod_zawodnika', 'kod_skoczka')

ans_4 = task4_df.groupby(['kod_zawodnika', 'nazwisko_imie']).punktacja.sum().sort_values(ascending=False).reset_index()

task_print(4)

ans_4.head(3)

-------------TASK-4-ANSWER-------------

  kod_zawodnika          nazwisko_imie  punktacja
0          sk11            STOCH Kamil       1094
1          sk25        KOBAYASHI Ryoyu        928
2           sk1  GRANERUD Halvor Egner        853

### Task 5

In [35]:
task5_df = merge_inner(zawody, skocznie, 'skocznia', 'kod_skoczni')
task5_df = task5_df[task5_df['punkt_K'] > 170]
task5_df = merge_inner(task5_df, skoczek, 'kod_zawodnika', 'kod_skoczka')
task5_df = merge_inner(task5_df, kraje, 'kod_kraju_y', 'kod_kraju')
task5_df = merge_inner(task5_df, punkty, 'miejsce', 'miejsce').rename(columns={'punkty_y': 'punktacja'})

ans_5 = task5_df.groupby(['kod_zawodnika', 'nazwisko_imie', 'nazwa']).punktacja.sum().sort_values(ascending=False).reset_index()
ans_5.head()

  kod_zawodnika        nazwisko_imie     nazwa  punktacja
0          sk25      KOBAYASHI Ryoyu   Japonia        189
1           sk7  EISENBICHLER Markus    Niemcy        171
2          sk62          PREVC Domen  Słowenia        160
3           sk6           ŻYŁA Piotr    Polska        139
4          sk11          STOCH Kamil    Polska        135

In [36]:
ans_5 = ans_5.iloc[0]
task_print(5)
print(ans_5['nazwisko_imie'], "|", ans_5['nazwa'], "|", ans_5['punktacja'])

-------------TASK-5-ANSWER-------------

KOBAYASHI Ryoyu | Japonia | 189

### Task 6

In [37]:
task6_df = merge_inner(zawody, skoczek, 'kod_zawodnika', 'kod_skoczka')
task6_df = merge_inner(task6_df, kraje, 'kod_kraju', 'kod_kraju')
task6_df = merge_inner(task6_df, skocznie, 'skocznia', 'kod_skoczni')

ans_6 = pd.pivot_table(task6_df, values='kod_zawodnika', columns='miasto', index='nazwa', aggfunc='count').replace(np.nan, 0)
task_print(6)
ans_6

-------------TASK-6-ANSWER-------------

miasto,Bischofshofen,Engelberg,Garmisch-Partenkirchen,Insbruk,Klingenthal,Lahti,Lillehammer,Niżny Tagił,Oberstdorf,Oslo,...,Predazzo,Rasnov,Ruka,Sapporo,Titisee-Neustadt,Trondheim,Vikersund,Willingen,Wisła,Zakopane
nazwa,,,,,,,,,,,,,,,,,,,,,
Austria,7.0,5.0,5.0,6.0,5.0,4.0,5.0,4.0,3.0,6.0,...,5.0,4.0,3.0,5.0,5.0,4.0,3.0,4.0,4.0,4.0
Bułgaria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
Czechy,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0,...,1.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0
Estonia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
Finlandia,1.0,1.0,1.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,1.0,0.0,1.0,0.0,2.0,1.0,1.0,0.0,0.0,1.0
Japonia,4.0,4.0,4.0,3.0,4.0,3.0,3.0,4.0,5.0,4.0,...,3.0,2.0,3.0,6.0,2.0,5.0,3.0,5.0,4.0,4.0
Kanada,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0
Niemcy,4.0,4.0,5.0,3.0,4.0,5.0,5.0,3.0,4.0,3.0,...,5.0,5.0,6.0,4.0,6.0,4.0,5.0,3.0,4.0,5.0
Norwegia,5.0,4.0,4.0,4.0,4.0,5.0,5.0,6.0,4.0,3.0,...,4.0,4.0,4.0,3.0,4.0,5.0,5.0,5.0,4.0,4.0
Polska,5.0,5.0,5.0,5.0,6.0,6.0,4.0,4.0,4.0,4.0,...,4.0,6.0,6.0,4.0,6.0,4.0,4.0,5.0,4.0,5.0
Rosja,2.0,1.0,1.0,1.0,1.0,0.0,1.0,3.0,1.0,1.0,...,0.0,2.0,0.0,0.0,0.0,1.0,3.0,1.0,3.0,0.0
Szwajcaria,0.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,...,2.0,2.0,2.0,1.0,0.0,2.0,1.0,2.0,3.0,0.0
Słowenia,2.0,4.0,3.0,4.0,4.0,4.0,2.0,4.0,4.0,3.0,...,4.0,4.0,4.0,5.0,2.0,2.0,4.0,3.0,4.0,5.0
Włochy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

### Task 7 
### a)

In [38]:
task7_df = merge_inner(zawody, skocznie, 'skocznia', 'kod_skoczni')
task7_df = merge_inner(task7_df, skoczek, 'kod_zawodnika', 'kod_skoczka')
task7_df = task7_df[(task7_df['odl.1'] > task7_df['punkt_HS']) | (task7_df['odl.2'] > task7_df['punkt_HS'])]


ans_7a = task7_df.groupby(['miasto']).kod_zawodnika.count().reset_index().rename(columns={'kod_zawodnika': 'suma'})
task_print('7a')
ans_7a = ans_7a[ans_7a['suma'] == ans_7a['suma'].max()]
ans_7a

-------------TASK-7a-ANSWER-------------

    miasto  suma
1  Insbruk     7

### b)

In [39]:
task7_df['ile_razy'] = (task7_df['odl.1'] > task7_df['punkt_HS']).astype(int) + (task7_df['odl.2'] > task7_df['punkt_HS']).astype(int)
ans_7b = task7_df.groupby(['nazwisko_imie']).ile_razy.sum().reset_index()
task_print('7b')
ans_7b[ans_7b['ile_razy'] == ans_7b['ile_razy'].max()]

-------------TASK-7b-ANSWER-------------

     nazwisko_imie  ile_razy
8  KOBAYASHI Ryoyu         6